title: 'projects'
subTitle: 'You will love our work. Check it out!'
projects:
  - id: 1
    image: 'images/front-page-project-1.jpg'

  - id: 2
    image: 'images/front-page-project-2.jpg'

  - id: 3
    image: 'images/front-page-project-3.jpg'

  - id: 4
    image: 'images/front-page-project-4.jpg'
